# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [59]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

import numpy as np



n1 = np.arange(1000000)
#print(n1)

my_list = list(range(1000000))


%time for _ in range(10):n2= (n1*2)
%time for _ in range(10):my_list2 = [i*2 for i in my_list]




Wall time: 129 ms
Wall time: 7.61 s


### Exercício 2

In [62]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

my_arr = np.arange(10)
my_arr[5:8]=0
my_arr

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

### Exercício 3

In [66]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
arr=[[12.13],[15,6],[10.9]]
arr[0]

[12.13]

### Exercício 4

In [97]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

arr=[[14,21,12],[12,59,87],[18,9,14]]
print(arr[2])
print(arr[0:2])
print(arr[1][1:3],arr[2][1:3])




[18, 9, 14]
[[14, 21, 12], [12, 59, 87]]
[59, 87] [9, 14]


### Exercício 5

In [5]:
# Calcule a transposta da matriz abaixo
import numpy as np
arr = np.arange(15).reshape((3, 5))
arr


arrT=arr.transpose()
print(arr)
print(arrT)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### Exercício 6

In [ ]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

### Exercício 7

In [14]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
from tempfile import TemporaryFile
import numpy as np
arrA = np.arange(10)




np.save(outfile, arrA)
outfile.seek(0) # Only needed here to simulate closing & reopening file
arrB= np.load(outfile)
arrB



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Exercício 8

In [ ]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

### Exercício 9

In [18]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

number                                              title  \
0    20975  Slicing columns with mixed types <str>,<int> f...   
1    20974  BUG: Fix drop_duplicates failure when DataFram...   
2    20970            performance when "combining" categories   
3    20969        Getting a ... in my CSV when using to_csv()   
4    20968                         Sharey keyword for boxplot   
5    20967   Column can be extended beyond DataFrame's length   
6    20966             BUG: Fix wrong khash method definition   
7    20965  BUG: Fix combine_first converts other columns ...   
8    20964  BUG: Index with integer data and datetime64[ns...   
9    20962  df.rank() has different behavior for python2 a...   
10   20960  DOC: add reshaping visuals to the docs (Reshap...   
11   20958  Using apply on a grouper works only if done af...   
12   20956  ENH: Return DatetimeIndex or TimedeltaIndex bi...   
13   20955  Building documentation fails with `ImportError...   
14   20954  Correlation inconsistencies between Series and...   
15   20951  Addressing multiindex raises TypeError if indi...   
16   20948  Indexing DataFrame with DateOffset is nearly i...   
17   20947        Allow drop bins when using the cut function   
18   20945  Data is mismatched with labels after stack wit...   
19   20944                       Drop rows based on condition   
20   20943  pd.read_sql does not handle queries that retur...   
21   20940                       unclear error with  read_sas   
22   20937  BUG: Series(DTI/TDI) loses the frequency infor...   
23   20936  __new__() missing 1 required positional argume...   
24   20932  API: expose `axis` keyword in pandas.core.algo...   
25   20930  DOC: Index.get_loc Cannot Accept List-like Tol...   
26   20928             Added script to fetch wheels [ci skip]   
27   20927  read_sas OverflowError: int too big to convert...   
28   20926   BLD: Lint for invalid files in wheels / packages   
29   20925  Series.reset_index(level_name, drop=True) acce...   

                                               labels state  
0                                                  []  open  
1   [{'id': 76811, 'url': 'https://api.github.com/...  open  
2   [{'id': 78527356, 'url': 'https://api.github.c...  open  
3                                                  []  open  
4                                                  []  open  
5                                                  []  open  
6   [{'id': 76811, 'url': 'https://api.github.com/...  open  
7   [{'id': 76811, 'url': 'https://api.github.com/...  open  
8                                                  []  open  
9                                                  []  open  
10  [{'id': 134699, 'url': 'https://api.github.com...  open  
11  [{'id': 76811, 'url': 'https://api.github.com/...  open  
12  [{'id': 49597148, 'url': 'https://api.github.c...  open  
13                                                 []  open  
14                                                 []  open  
15                                                 []  open  
16                                                 []  open  
17  [{'id': 76812, 'url': 'https://api.github.com/...  open  
18                                                 []  open  
19                                                 []  open  
20                                                 []  open  
21                                                 []  open  
22                                                 []  open  
23                                                 []  open  
24  [{'id': 35818298, 'url': 'https://api.github.c...  open  
25                                                 []  open  
26  [{'id': 131473665, 'url': 'https://api.github....  open  
27                                                 []  open  
28  [{'id': 129350, 'url': 'https://api.github.com...  open  
29  [{'id': 42670965, 'url': 'https://api.github.c...  open

### Exercício 10

In [45]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas


import sqlite3

conn=sqlite3.connect('paciente.db')
conn

cur=conn.cursor()

sql_create = 'create table paciente '\
'(id integer primary key , '\
'titulo varchar(100), '\
'categoria varchar(140))'

cur.execute(sql_create)

In [54]:
sql_insert = 'insert into paciente values (?,?,?)'
recset = [(4, 'Maria Aparecida', 'F000000000000000000'),
          (46, 'José Antonio', 'M000000000000000'),
          (13, 'Maldonado jorge', 'M000000000000000000000')]

In [43]:
recset = [(1234, 'Maria Aparecida','F'),
         (4356, 'Jose Antonio','M'),
          (3456, 'Maldonado Antonio','M')]




In [56]:
for rec in recset:
    cur.execute(sql_insert, rec)
conn.commit()

IntegrityError: UNIQUE constraint failed: paciente.id

In [58]:
sql_select = 'select * from paciente'
cur.execute(sql_select)
dados = cur.fetchall()



In [63]:
from pandas import DataFrame
df= DataFrame(dados)
df


0                1                       2
0     4  Maria Aparecida     F000000000000000000
1    13  Maldonado jorge  M000000000000000000000
2    46     José Antonio        M000000000000000
3   123  Maldonado jorge                       M
4  1234  Maria Aparecida                       F
5  4356     José Antonio                       M

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>